import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen">
        <div className="flex h-full w-full items-center justify-center">
          <div className="items-center justify-center max-w-md bg-gray-50 px-4 py-8 rounded-md">
            <h1 className="font-bold text-2xl text-center">Geek</h1>
            <hr className="my-2" />
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique
              tempora voluptatem dolores sequi soluta. Voluptas nihil aperiam
              alias sit nesciunt fugit, odit et quaerat, culpa illo id quasi
              repellendus ea?
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
